name: moviedb
description: Movie DB Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  youtube_player_flutter: ^8.0.0

  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.4
  google_fonts: ^2.2.0
  ionicons: ^0.1.2
  simple_animations: ^4.0.1
  percent_indicator: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
   - assets/images/
